### ISSUE TITLE
BUG: refresh home details

### ISSUE THREAD

**Issue by paulcalabro** [victorbalssa/abacus#104]
**Describe the bug**
Pulling down in the app to manually refresh balance data does not update the net worth panel at the top.

**To Reproduce**
1. Go to 'Home' with the 'Accounts' tab selected
2. Swipe down to initiate a sync
3. Observe balance data updates but net worth data for period does not update (you need to change the period and come back to the same period to refresh the data)

**Expected behavior**
All balance and net worth data is refreshed

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 17.0
 - Version 0.8.1

**Additional context**

**Comment by a7maadf** [comment]
I confirm having the same issue
