### ISSUE TITLE
BUG_Not all Currencies are listed

### ISSUE THREAD

**Issue by gpampuro** [victorbalssa/abacus#105]
**Describe the bug**
In the main screen when selecting the currency, it only shows the first 20-25 currencies. I have more currencies in the app and I cannot see other currencies than the first 20 or 25 of them.

**To Reproduce**
1. Go to Main Screen
2. Click on Currency Dropbox
3. Scroll down to the end
4. Not listing more than 20/25 currencies

**Expected behavior**
The list should show all the currencies created in the website

**Smartphone (please complete the following information):**
 - Device: iPhone 14Pro
 - OS: iOS 17
 - Version Abacus 0.8.1

**Comment by victorbalssa** [comment]
Hey @gpampuro,

Closing this one. You can fix it with a preference setting on FireflyIII:
- Go to https://your_url_firefly_iii.com/preferences
- Go to tab Layout
- Set your `page size` to a number bigger than the total number of your currencies
- save & reload Abacus

![image](https://github.com/victorbalssa/abacus/assets/12813321/e011004d-48a3-4e50-9d23-84695583ba40)

That's it!

Reason: I don't think there are a lot of FireflyIII users with more than 20 active currencies.
