### ISSUE TITLE
Feature Request: Momentjs translation with current locale.

### ISSUE THREAD

**Issue by s4w4j4** [victorbalssa/abacus#108]
Function Request: Translate the months in the date into Chinese

![IMG_60F7CCD006AD-1](https://github.com/victorbalssa/abacus/assets/90949008/54aa5bbb-db85-4d2a-b851-2248a40e493e)

**Comment by s4w4j4** [comment]
Can you please help me take a look at this request? thanks  @victorbalssa

**Comment by victorbalssa** [comment]
> Can you please help me take a look at this request? thanks @victorbalssa

@s4w4j4 I will look into this one for the next release.

**Comment by s4w4j4** [comment]
In version 0.9.1, the date of the new transaction has been changed to Chinese, but the date on the homepage is still in English. Please help to check this issue. thanks @victorbalssa 

![image](https://github.com/victorbalssa/abacus/assets/90949008/1fe3679c-d8c4-4168-93a9-85924baf77ff)

![image](https://github.com/victorbalssa/abacus/assets/90949008/74199e55-4560-4f08-b8fd-66cc92e0b35d)

**Comment by s4w4j4** [comment]
Updated 0.9.2, the issue still persists

**Comment by victorbalssa** [comment]
@s4w4j4 This should be fixed with the last Over the Air Update `0.9.3`.
