### ISSUE TITLE
Month is incorrect monthly transaction list

### ISSUE THREAD

**Issue by klejejs** [victorbalssa/abacus#12]
Going to transaction view and selecting monthly report, month shown on the top of the page is one earlier than selected, e.g., when I select July, the text says June.

P.S. Hey! I really appreciate you working on this app, I love it. Thanks and keep up the good work. I just installed the latest version and started using it, there are unfortunately a few bugs, so I'll report them separately.

**Comment by victorbalssa** [comment]
Awesome! 

@klejejs Thank you for your reporting.

I will fix those and get back to you when it's done.
It might just need a 2x reload of the app without any updates from the store.

Vic
