### ISSUE TITLE
Bug: incorrect currency + make destination not required.

### ISSUE THREAD

**Issue by michelebossa** [victorbalssa/abacus#124]
Hi,
Hi have just update and i see this two problems during new transaction filling:

- incorrect currency USD but my default it is EUR
- destinazione account it is indicated as mandatory but it is not usually i leave blank.

![Screenshot_20230827_210356_Abacus.png](https://github.com/victorbalssa/abacus/assets/38975058/a5b8184c-c9a9-4c3c-b4e5-43d9a8c314b0)
 
Can you check?

Thanks

**Comment by s4w4j4** [comment]
I have no other currency besides the built-in Euro and default RMB currency. The new interface has two places for inputting amounts, and they are still in US dollars, which makes me feel at a loss and unsure how to use them.

**Comment by victorbalssa** [comment]
Fixed in #132
