### ISSUE TITLE
Feature request: gray out "add split" btn + Localize date selector

### ISSUE THREAD

**Issue by s4w4j4** [victorbalssa/abacus#125]
1. When creating a new transaction, there are two text boxes for entering the amount, and both are in default US dollars. When using only RMB as the default single currency, can we only display a text box for entering the amount and use the default RMB as the currency instead of the default US dollar?

2. My language is Chinese, but the month is still English. Please help me check this issue.

3. When creating a new transaction, there are two buttons at the bottom, which makes me unsure which button to press. Creating a new transaction should only require a submit button. Can you optimize it.

I use a Chinese English translation, and if there are any inappropriate expressions, please forgive me. thanks

![image](https://github.com/victorbalssa/abacus/assets/90949008/8c064422-a9bd-475d-845c-b65100d2df68)
![image](https://github.com/victorbalssa/abacus/assets/90949008/22e9acd7-1678-43ff-b904-3e8f7a2f2d09)

**Comment by victorbalssa** [comment]
Fixed in #132
