### ISSUE TITLE
BUG_Android version states iOS storage

### ISSUE THREAD

**Issue by akmzero** [victorbalssa/abacus#127]
**Describe the bug**
On initial log in screen for Android version, app states secrets stored in iOS storage

**To Reproduce**
1. Go to initial login page
2. Incorrect information on bottom

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro

![Screenshot_20230830-162732.png](https://github.com/victorbalssa/abacus/assets/603954/01f2603d-5791-4376-beb5-ae6d92d7331b)

**Comment by MaoMaoCake** [comment]
also in the settings tab it's FaceID lock, let's call it biometrics

ps I dotn think this warrants a new issue since it's still a translation/text bug

**Comment by victorbalssa** [comment]
Fixed in #132
