### ISSUE TITLE
BUG_Url validation

### ISSUE THREAD

**Issue by naxvog** [victorbalssa/abacus#130]
**Describe the bug**
Currently it is impossible to login to a local instance by only it's hostname if it isn't following the [domain].[tld] schema.

**To Reproduce**
Try logging into a local instance via its hostname

**Expected behavior**
It is possible to login into a local instance 

**Screenshots**
![Screenshot_20230905-075036.jpg](https://github.com/victorbalssa/abacus/assets/4963183/0171197d-6b72-419f-8124-4fce6d061b8f)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6t
 - OS: Android 11
 - Version (App) 0.9.0

**Additional context**
- using an IP will work as a workaround

**Comment by victorbalssa** [comment]
Fixed in #132
