### ISSUE TITLE
BUG_GROUP_TITLE_MUST_BE_1_TO_1000_CHARACTERS

### ISSUE THREAD

**Issue by MaoMaoCake** [victorbalssa/abacus#134]
**Describe the bug**
Updating transactions that exist  errors out 

**To Reproduce**
1. Go to transactions
2. Click on any transaction - no need to edit 
3. Scroll down and try to submit

**Expected behavior**
Transaction gets updated

**Screenshots**
![Screenshot_20230908-130225_Abacus.jpg](https://github.com/victorbalssa/abacus/assets/55589246/3f42eefe-7f54-4d6a-990d-6265e6a56d43)

**Smartphone (please complete the following information):**
 - Device: s10e
 - OS: Android​11
 - Version 0.9.1

**Additional context**

**Comment by victorbalssa** [comment]
Hey @MaoMaoCake,

I will need more infos to reproduce this issue:

- Is this a split transaction? was a split transaction? 
- Does it happen each time you want to edit any type of transaction?   
- Do you have the same issue on FireflyIII dashboard?

**Comment by MaoMaoCake** [comment]
> - Is this a split transaction? was a split transaction? 
no it's a normal transaction 

> - Does it happen each time you want to edit any type of transaction?
yes
   
> - Do you have the same issue on FireflyIII dashboard?
> 
no

I'm on firefly 6.0.15 if that matters.

**Comment by MaoMaoCake** [comment]
hi, update on the issue I've updated tm firefly to 6.0.23 and it's working fine now. I guess you can lower this on your priority

**Comment by victorbalssa** [comment]
@MaoMaoCake 
Thanks for the update, I will probably create a minimum supported version for FireflyIII soon 👍🏻
