### ISSUE TITLE
Add support for custom headers to connect to the backend

### ISSUE THREAD

**Issue by Mirabis** [victorbalssa/abacus#137]
**Describe the solution you'd like**
An option to add custom headers to the request which can be used to authenticate with the cloudflare (or other solution) tunnels.  Cloudflare specifically allows `CF-Access-Client-ID` and `CF-Access-Client-Secret`

By passing those I can securely provide access to the app and exclude all other undefined requests.

**Describe alternatives you've considered**
N/A

**Additional context**
https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/

**Comment by victorbalssa** [comment]
After some research around headers and requirements I decided that it would be to complicated and add to much complexity in the app to support customs headers object with the creation of new screens, forms, etc. 

I prefer to focus on existing FireflyIII features.
