### ISSUE TITLE
BUG_ Auto refresh home details

### ISSUE THREAD

**Issue by accountForIssues** [victorbalssa/abacus#139]
**Describe the bug**
Unlike the transactions page which refreshes when clicked, the home page has to be refreshed manually.
(I spent way too much time to check why the balances were differing until I realised it just didn't refresh :P)

**To Reproduce**
1. Add a txn via WebUI or app.
2. Close and re-open the app.
3. Does the home page reflect the new balance ?

**Expected behavior**
Home page should refresh on initial open of the app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 13

**Additional context**
Additionally, there could also be a tiny label with the last sync time shown to avoid any confusion.

**Comment by victorbalssa** [comment]
Thanks @accountForIssues, I will reload the home details on first load 🆗
