### ISSUE TITLE
BUG_ Create transaction button crashes the app

### ISSUE THREAD

**Issue by klejejs** [victorbalssa/abacus#14]
**Describe the bug**
Opening the app and clicking the add transaction button, the app immediately crashes.

**To Reproduce**
1. Open app
2. Click on add transaction button in middle
3. See the app crash.

**Expected behavior**
I guess a new window should open

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 15.5
 - Version: 0.9

**Additional context**

**Comment by victorbalssa** [comment]
Hi @klejejs, 
Thanks,

I can't reproduce the bug I tried multiple configurations server-side.

After reseting everything with the `Clear & Reset Application` btn in `Settings`tab does the app continue to crash?

It might be due to some old data stored from previous versions (Alpha).

Let me know.

**Comment by victorbalssa** [comment]
I found the bug.

It will be fix in the next release 0.1.0.
