### ISSUE TITLE
Feature Request: Hide balances

### ISSUE THREAD

**Issue by afonsoc12** [victorbalssa/abacus#145]
**Is your feature request related to a problem? Please describe.**

When storing on the go, I don’t want net worth displayed when opening the app. Would be great to have a way to hide balances

**Describe the solution you'd like**

Simple button to hide all balances and NW

**Describe alternatives you've considered**

N/A

**Additional context**

Apologies if this has been requested

**Comment by afonsoc12** [comment]
Just updated and it looks amazing. Thank you for implementing this so swiftly!

**Comment by afonsoc12** [comment]
I was just wondering if there is a setting to store the hidden state or save last state.
Everytime you re-open the app, the NW number will be visible. Is it possible to reuse the last state?

**Comment by victorbalssa** [comment]
I will add this to config model 👍🏻
