### ISSUE TITLE
BUG_CRASH_ON_ADD

### ISSUE THREAD

**Issue by whiteemikee** [victorbalssa/abacus#146]
**Describe the bug**
The app crashes when the "+" button is pressed. 

**To Reproduce**
1. Open the app
2. Click on '+'
3. See that app crashes

**Expected behavior**
The "Add" dialog should open.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 16.1.1
 - Version 0.9.2

**Comment by victorbalssa** [comment]
Hey @whiteemikee,

Can you try to `Clear & Reset Application` under `Settings` tab?

This will reset local stored data and should fix old structure that may throw this error.

If this does not work, can you try another login method (Personal Token or OAuth2.0)?

Let me know if this is working or not,
Thank you

**Comment by whiteemikee** [comment]
I tried your suggestion to clear and reset the app from the app's settings tab then reconnected using a Personal Access Token. Unfortunately the app is still crashing when the "+" button is pressed.

**Comment by victorbalssa** [comment]
What's your FireflyIII version? can you update it to the last version e.g. `6.0.26`.

**Comment by victorbalssa** [comment]
@whiteemikee do you still encounter this bug with the last FireflyIII version?

**Comment by whiteemikee** [comment]
Apologies for the delay. I attempted to update my Firefly install this morning but it was not successful. My current version is `6.0.24` running as a docker container in a TrueNAS Scale instance. I will attempt an upgrade this weekend.

**Comment by Sn0wed1** [comment]
I am also experiencing this issue. The crashing behavior also occurs when trying to edit a transaction in the transactions tab.

**Smartphone (please complete the following information):**
    Device: iPhone SE (2nd Generation)
    OS: iOS 17.03
    Version 0.9.2
    Display Resolution: 1334 x 750 [pixels]
    Pixel Density: 326 ppi


**Firefly III Environment:**
    Install: Docker [fireflyiii/core:latest]
    Version: 6.0.27

The app doesn't crash on the following devices. The connection details are the same across all devices.

**Smartphone (please complete the following information):**
    Device: iPhone XS
    OS: iOS 17.1 (Beta)
    Version 0.9.2
    Display Resolution: 2436 x 1125 [pixels]
    Pixel Density: 458 ppi

**Smartphone (please complete the following information):**
    Device: iPad  (7th Generation)
    OS: iOS 17.03
    Version 0.9.2
    Display Resolution: 2160 x 1620 [pixels]
    Pixel Density: 264 ppi
