### ISSUE TITLE
Bug: date selector in wrong language (Italian instead of English or Dutch)

### ISSUE THREAD

**Issue by L-E-0-N** [victorbalssa/abacus#147]
Hi,

The whole app is English for me which is perfect only the date selector is in Italian? And I’m Dutch myself so it’s quite weird.

![IMG_6849](https://github.com/victorbalssa/abacus/assets/23658130/6b87d3f1-29ec-4cd4-8d0b-fd81666a1594)

**Comment by victorbalssa** [comment]
Thank for reporting this, looks like it's linked to #108.

I just OTA a new patch (update in app, you might need to reload the app to dl the update), let me know if this fix your issue.

**Comment by L-E-0-N** [comment]
> Thank for reporting this, looks like it's linked to #108.
> 
> I just OTA a new patch (update in app, you might need to reload the app to dl the update), let me know if this fix your issue.

Perfect! Just reloaded and it’s all fixed now, thanks for the quick solution!
