### ISSUE TITLE
BUG_HTTPS Call Not working

### ISSUE THREAD

**Issue by Roxas2712** [victorbalssa/abacus#15]
**Describe the bug**

**To Reproduce**
1. Go to Abacus App and try to call your Firefly via your HTTPS Link
4. See error: Offline - You are probably offline. Firefly III is Not reachable.

**Expected behavior**
My expectation was that I can use HTTPS for a more safety call via reverse proxy to use the app everywhere. The normal call of firefly via https in my browser is just working fine. 

**Screenshots**
![0DEFC8AC-80AB-4944-88CE-2DCBB3BE363C](https://user-images.githubusercontent.com/41802861/180188263-1c3bcefd-d256-4b69-a57b-c77179fb29d8.jpeg)
![6426F4D8-7E61-498C-ACCF-CEE9EED17669](https://user-images.githubusercontent.com/41802861/180188273-20d38f6f-ca3f-446b-9de6-6779f4a3d9ff.jpeg)

**Smartphone (please complete the following information):**
 - Device: IPhone 12ProMax
 - OS: IOS 15.5
 
 **Additional Context**
 Not sure if this is really a bug or just a „missing“ functionality. It would be really great if those calls are possible to let as many ports as possible untouched.

**Comment by victorbalssa** [comment]
Hi @Roxas2712,
Thanks for the feedback,

Do you have access to your FireflyIII instance from Safari with `HTTPS` enabled?

This is not the normal behaviour, if you can get access to your instance with `HTTPS` but can't with **Abacus** can you share what reverse proxy do you use ?

**Comment by Roxas2712** [comment]
Im using a synology reversed proxy via https -> http.

But maybe the certificate is the problem. In every browser I need to allow the access for https access. I don’t know if this option maybe is not coming up and therefore I get this error. Just an idea

**Comment by victorbalssa** [comment]
I think the best would be to use a trusted SSL certificate with HTTPS, or completely remove HTTPS (only if the instance isn't connected to internet and you can trust your LAN).

I use an expo library to handle the oauth workflow, I'm not sure if you can accept fake certificate  https://docs.expo.dev/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl-options

**Comment by Roxas2712** [comment]
Unfortunately I need to use HTTPS :/  I would like to use abacus to quickly write entrys directly after shopping etc. so our idea to use this tool was for us more like an „instant“ tracking of our family finances. this is the reason also for my other weird questions. I will try to get a certificate that works., and let you know once I solved it. Thank you:)

**Comment by victorbalssa** [comment]
Yw
