### ISSUE TITLE
BUG_The total assets of the account are not displayed based on the selected month

### ISSUE THREAD

**Issue by s4w4j4** [victorbalssa/abacus#159]
**Describe the bug**
The total assets of the account are not displayed based on the selected month.

![image](https://github.com/victorbalssa/abacus/assets/90949008/22be7ade-346f-4273-aace-c3f6e152ddd4)

**Comment by s4w4j4** [comment]
For example, when selecting September, the total assets for the current month (October) will still be displayed.

**Comment by victorbalssa** [comment]
@s4w4j4 
Yes, it was design this way to avoid confusion when checking previous months.
But we still display difference for each month.
