### ISSUE TITLE
BUG_Edit transactions issue

### ISSUE THREAD

**Issue by ahmaddxb** [victorbalssa/abacus#160]
**Describe the bug**
If you currently have a withdrawal transaction and edit it to be a transfer transaction, and then click 'Submit,' it will say 'Success,' but it will still remain a withdrawal transaction in the transaction list in the app and also if you open firefly III in the browser.

**To Reproduce**
1. Go to transactions .
2. Click on a current withdrawal transaction to edit it.
3. Change transaction type to transfer.
4. Fill in the necessary field and click submit.
5. Go back to transactions list and see that the changes have not saved.

**Expected behavior**
It should convert a withdrawal transaction to a transfer transaction.

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 13
 - Version 0.9.2

**Comment by victorbalssa** [comment]
@ahmaddxb there is no possibility to switch directly from a Expense to a Transfer or Deposit, I will remove the unneeded Type selector.

We can duplicate and then choose the right type if needed 👌🏻

**Comment by ahmaddxb** [comment]
It's possible from the Web interface. You can convert it to a transfer. Maybe in you app if not from the edit form perhaps you hold down on the transaction and it gives you the option to convert to transfer or deposit. This would populate a new form with existing data except an empty destination field

![Screenshot_20231106_213602_Chrome.jpg](https://github.com/victorbalssa/abacus/assets/43728586/eb52fcee-733b-49cc-9544-3c2281011e42)

**Comment by victorbalssa** [comment]
@ahmaddxb unfortunately the API endpoint doesn’t exit, it exist only on the Laravel interface.
https://api-docs.firefly-iii.org/
