### ISSUE TITLE
BUG_Cloned transactions seem to have extra data in name

### ISSUE THREAD

**Issue by accountForIssues** [victorbalssa/abacus#161]
**Describe the bug**
If I clone a transaction via the app, the name seems to be prefixed with "Default tltle: " on the home page of the dashboard.

I also wonder if it's on the server side as the "Default title: " is not present anywhere (not even the app) except the home page. However, it only appears if I close the transaction via the app and not via the dashboard so I dunno what the dashboard is doing differently. So, filing a bug here to start.

**To Reproduce**
1. Clone a transaction using the app.
2. Check the new transaction on the home page in the dashboard.

**Screenshots**
![image](https://github.com/victorbalssa/abacus/assets/52367365/548da5a8-f037-4343-b0df-7771cb2e4593)

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 13

**Comment by Madekuji** [comment]
After some experimentation, I found that this extra data is actually the **title of a split transaction**. You can test this by going to a transaction that has the "Default title" extra data and making a split transaction and you'll find the title there.
![image](https://github.com/victorbalssa/abacus/assets/27665110/ccaa964b-f7dc-449d-b598-fd759626b50d)

I assume that the bugfix is to prevent this from happening, but it doesn't resolve existing transactions with this issue as Firefly III doesn't seem to have an issue with individual non-split transactions having a split transaction title.

The way to remove this is to go through all of your transactions that has a "Default title", then for each matching transaction, create a split, clear the "Default title", then delete the split and update the transaction.

**Comment by victorbalssa** [comment]
Thanks @Madekuji I'll always display the group title to be able to fix this 👍🏻

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.
