### ISSUE TITLE
Feature Request: display filter on top of transactions screen 

### ISSUE THREAD

**Issue by ahmaddxb** [victorbalssa/abacus#164]
**Describe the bug**
Transfers from a USD account to another USD account are not visable in the app transactions screen.

If i do a transfer from USD account to an AED account with foreign amount then it will be displayed in the transactions list.

My default currency is AED

**Expected behavior**
All transaction be displayed in the list

**Screenshots**

![image](https://github.com/victorbalssa/abacus/assets/43728586/5a267984-2c8b-49ac-884f-d712a0bc6461)

![image](https://github.com/victorbalssa/abacus/assets/43728586/41bb80d0-b302-4f5d-8772-29ed95ab5f86)

![image](https://github.com/victorbalssa/abacus/assets/43728586/35952d24-f421-4405-b1e9-80228e20b16e)

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 13
 - Version 0.9.2

**Comment by victorbalssa** [comment]
Hey @ahmaddxb, you need to select `USD` in the Home tab to see all `USD` transactions.

Probably not the best filter setup, I'm working on this.

**Comment by ahmaddxb** [comment]
Oh I see. Thanks for letting me know.
