### ISSUE TITLE
BUG: handle new access token workflow from refresh token.

### ISSUE THREAD

**Issue by Kage1** [victorbalssa/abacus#170]
**Describe the bug**
After not using the app for a week or two when launching it I get Something went wrong multiple times. The URL in the app is gone and I have to clear storage and set it up again.

**To Reproduce**
1. Let it sit for some period of time
2. Open and get the error

**Expected behavior**
Launch & connect to the ff3 instance

**Screenshots**
See attached
![Screenshot_2023-11-03-07-58-30-10_99ee85e1449b867412b241cdd17782b1.jpg](https://github.com/victorbalssa/abacus/assets/2062390/b6693e0f-eb9a-4991-9671-0cd8028d90f2)

![Screenshot_2023-11-03-07-58-13-90_99ee85e1449b867412b241cdd17782b1.jpg](https://github.com/victorbalssa/abacus/assets/2062390/5d67729a-2efd-4b77-87af-dcdb45a88805)

**Smartphone (please complete the following information):**
 - Device: 1+8T
 - OS: Android 
 - Version 13

**Additional context**
I have it on two different devices and both of them had this issue. They are using separate oauth client IDs/secrets. Ive had my device do it twice.

I checked after the app errored out and the ff3 instance was up and healthy.

One thing I noticed on both, the URL was blanked out.

After clearing the storage and setting up the app again using the same client/secret it connects and works.

**Comment by victorbalssa** [comment]
@Kage1 can you try to clear & Reset the application and re-do the Authentication?
Something with the cache I didn't had the time to automatically clear it.

**Comment by Kage1** [comment]
On my device it was so hung I couldn't get to any menu.

Device #2 the clear reset worked.

One other interesting thing last night when my wife tried to use device #2 I got an automailer from ff3 with:

"Somebody (hopefully you) just created a new Firefly III API Access Token for your user account."

It was like the token had timed out and had to be reissued and maybe Aba isn't handling it well?

**Comment by victorbalssa** [comment]
Yep basically the access token only last 2 weeks or so, refresh token will be used to recreate a new access token, that's why you had this email from ff3.

I think I will rename this issue to: BUG: handle new access token workflow from refresh token.

Something is missing and the `URL` seems to reset to early.
