### ISSUE TITLE
BUG: Destination accounts do not include a generic "Cash account"

### ISSUE THREAD

**Issue by klejejs** [victorbalssa/abacus#176]
**Describe the bug**
Firefly III provides a generic cash account that is not shown in any accounts list but can be a target during transactions:
![image](https://github.com/victorbalssa/abacus/assets/24546950/830c40f4-d644-45b2-a555-f2dac9e7b980)

**To Reproduce**
1. Go to new transactions view
2. Search for cash account
3. It is not there

**Expected behavior**
It would be nice if it was added to the list as well.

**Smartphone (please complete the following information):**
 - Device: iPhone14
 - OS: iOS17
 - Version 0.10.0

**Comment by victorbalssa** [comment]
@klejejs Is this an `Expense` or `Revenue` account?

These accounts are a bit different as they represent total expenses or total income.

As long as the cash account is an asset account no matter the `Account role` it will be displayed in Abacus (status `active`).
![image](https://github.com/victorbalssa/abacus/assets/12813321/7f60f005-41ab-4be5-853f-e99ac574caf4)

**Comment by klejejs** [comment]
@victorbalssa I think it counts as an Expense account. But as I said, as far as I know, it is not in any accounts list, you can see it only when creating a new withdrawal and you have already set the source account as an asset account. It is basically a way of making money disappear :D 
![image](https://github.com/victorbalssa/abacus/assets/24546950/ac42c064-c9e4-40ff-a7f7-95872e4fc4da)

**Comment by victorbalssa** [comment]
This is represented as `(cash)` but it's the default `blank` account, basically you can use it in Abacus by leaving the `Destination account` black and then save.

https://docs.firefly-iii.org/firefly-iii/financial-concepts/tracking_cash/

**Comment by klejejs** [comment]
Thanks for explanation!
