### ISSUE TITLE
Switching to Charts View Forces Login Flow

### ISSUE THREAD

**Issue by paulcalabro** [victorbalssa/abacus#188]
**Describe the bug**
Switching to the charts view causes the login flow to occur. It doesn't appear to affect the transaction view.

**To Reproduce**
1. Log in with a personal access token 
2. Navigate to the charts view
3. This causes the app to force the login flow 

**Expected behavior**
I do not get logged out

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 17.2
 - Version 0.10.1

**Additional context**

**Comment by victorbalssa** [comment]
@paulcalabro 
I was wondering if the last version fixed this issue?

**Comment by paulcalabro** [comment]
Sorry @victorbalssa for the late response, just saw your message. It did not. I tested this out a few days ago (not sure what version, but I'm fairly current) and it triggered the login flow.

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if the charts don't work.

**Comment by paulcalabro** [comment]
Just confirming that this resolved the issue. Thank you!
