### ISSUE TITLE
BUG: Tag text area reset after selecting from dropdown list

### ISSUE THREAD

**Issue by qck4fun** [victorbalssa/abacus#195]
**Describe the bug**
When selecting a tag from drop-down list, text area is not reset, which without manual correction leads to creation of a new tag. In attached screenshot it leads to creating new `Al` tag.

**To Reproduce**
1. Go to create a new transaction
2. Fill-up all mandatory fields + try to select already existing tag by typing part of it's name
3. App shows you drop-down list from which you select the tag
4. Text area keeps the partial tag name present, which after saving transaction creates a new tag

**Expected behavior**
After selecting a tag from drop-down list, text area should be set to `null` or so.

**Screenshots**
![image](https://github.com/victorbalssa/abacus/assets/7276555/6674d052-50b4-4a26-8e0a-93123fd619b0)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 16.6
 - Version 0.10.2

**Additional context**
Not a major thing, but mere inconvenience.

**Comment by purevsurena** [comment]
Could you please clarify whether this task is available for me to undertake, or if another individual has already been assigned to it?

**Comment by victorbalssa** [comment]
Hey @purevsurena, this is not started yet I always self-assign issues by default.
If you want to tackle this, just let me know I will assign this to you.

Feel free to create a PR for this issue and tag me for the review 👍🏻

**Comment by purevsurena** [comment]
Thank you for your answer, I got it. Please reassign this task to me, and I'll take care of it.

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.
