### ISSUE TITLE
BUG_ iOS: tapping the graphs tab crashes the app

### ISSUE THREAD

**Issue by el-tiuri** [victorbalssa/abacus#196]
**Describe the bug**
On the latest version of the app it crashes when tapping on the graphs tab

**To Reproduce**
1. Open the app
2. Click on the graphs button
3. The app crashes and closes

**Expected behavior**
The graphs tab is displayed

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 17.1.1.
 - Version 0.10.2

**Additional context**
This used to work in previous versions, so this was introduced in the last or second to last update.

**Comment by victorbalssa** [comment]
Hey @el-tiuri,
Can you try to Clear cache and reset application and re-log into your FireflyIII instance?

Let me know if that works,
If not can you share with me the version of fireflyIII you have?
Thanks

**Comment by el-tiuri** [comment]
Resetting it didn’t work, reinstalling the app did.

**Comment by victorbalssa** [comment]
Ok interesting… must be something with iOS keychain storage then.
Closing then 💯
