### ISSUE TITLE
BUG: Workflow token handling not completing

### ISSUE THREAD

**Issue by Kage1** [victorbalssa/abacus#197]
**Describe the bug**
A continuation of #170.

The token timed out again and it kept the URL this time, but the Client ID and secret fields were blanked out.

**To Reproduce**
1. Enter URL, token and secret
2. Access instance
3. Wait till the token times out
4. App throws an error when attempting to refresh it.

**Expected behavior**
Token gets refreshed and data is available.

**Screenshots**
![Abacus Error 111823](https://github.com/victorbalssa/abacus/assets/2062390/dce7a271-6f52-486a-829a-3af9f14335fa)

**Smartphone (please complete the following information):**
 - Device: 1+8T
 - OS: Android
 - Version 13

**Additional context**
Saw this on both of my devices, same type, same OS.

**Comment by Kage1** [comment]
Forgot this in the original post, after adding the ID and secret the client connected as expected.

**Comment by Kage1** [comment]
One more update: So, on my other device it threw the error above. After closing the app and going back into it, it connected and I got the email from FF3 that a new token was created. Not sure what to make of this.

**Comment by victorbalssa** [comment]
Thanks @Kage1!

> One more update: So, on my other device it threw the error above. After closing the app and going back into it, it connected and I got the email from FF3 that a new token was created. Not sure what to make of this.

-> After closing the app it connected you, without needing to enter anything (OAuth id/secret) ?

**Comment by Kage1** [comment]
> Thanks @Kage1!
> 
> > One more update: So, on my other device it threw the error above. After closing the app and going back into it, it connected and I got the email from FF3 that a new token was created. Not sure what to make of this.
> 
> -> After closing the app it connected you, without needing to enter anything (OAuth id/secret) ?

Yea it connected and shortly after I got the token issued email, this was on device 2.

On device 1 I manually reentered it but my guess is it would  have worked also on the 2nd try.

**Comment by Kage1** [comment]
An update, this morning it threw the error since the token has timed out. I did get the email from ff3 that a new token was issued, but the Aba login wouldn't update till I put the ID and Secret back in. After that I got another email that another token was issued.

![signal-2023-12-09-101825_002](https://github.com/victorbalssa/abacus/assets/2062390/cd3a350b-62d2-40eb-9e17-dfb1bce4d521)

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.

**Comment by Kage1** [comment]
An observation,

There is a breaking change, the redirect URL changed from:

abacusiosapp://redirect
to
abacusfiiiapp://redirect

At least for the Android app.

I'll see In a few weeks how it goes with the token refresh issue.

**Comment by victorbalssa** [comment]
Yes I forgot to mention this in the changelog, you need to update the redirect URL ([here](https://github.com/victorbalssa/abacus/blob/updates/.github/HELP.md)) to `abacusfiiiapp://redirect` in order to login again via OAuth. All current token should still work as expected but next time you login it will throw an error if you use the old `abacusiosapp` scheme.
