### ISSUE TITLE
BUG: Cloning problem with group title, always display group title

### ISSUE THREAD

**Issue by creylopez** [victorbalssa/abacus#203]
Whenever I clone a transaction, it fails when submitting, even if no fields are changed. 
![IMG_6858](https://github.com/victorbalssa/abacus/assets/54448654/7a5c98e5-8211-461d-9c42-b51227e36a6a)

**Comment by victorbalssa** [comment]
Hey @creylopez, I think you can clear the foreign currency and retry, it should work.

**Comment by creylopez** [comment]
Well, it was empty but I clicked in the small X to clean whatever could be there. Now the error is "This value is not valid for this field".

I just clone the entry and click in Send. No changes and the error arises.

**Comment by victorbalssa** [comment]
Can you share the full transaction details without the description please?

**Comment by creylopez** [comment]
how to you want the details? a screen shot? Indeed, it fails with any transaction. I just created a sample one and try to clone it.

**Comment by creylopez** [comment]
Disable some currency…where? App (don’t know how to do that) or server (could be, need to check)

nevertheless, something similar happens just by editing one entry. See screen shots attached. 
![IMG_6890](https://github.com/victorbalssa/abacus/assets/54448654/d0a251e6-9dbb-4572-a7ce-d5cddb476285)
![IMG_6891](https://github.com/victorbalssa/abacus/assets/54448654/9d6c3631-f795-4e99-a054-c0b01676eef4)
![IMG_6892](https://github.com/victorbalssa/abacus/assets/54448654/9fab01b8-6a88-4dd8-ad76-cddc1a08d6c9)

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.

**Comment by creylopez** [comment]
Well, it seems that the problem persists. Furthermore, now in the home screen if when refreshing Accounts, nothing appears and it raises an error "Something went wrong. Request failed with status code 404

**Comment by creylopez** [comment]
Apart from the previous post, I think you should update the help page, it says that the redirect url is **_abacusiosapp_** when it should say _abacusfiiiapp_ as mentioned in the app itself.

**Comment by victorbalssa** [comment]
Thanks @creylopez, I updated the Help page.

For the account issue, can you share with me the version of FireflyIII you are using? I think it needs the last version.

**Comment by creylopez** [comment]
Firefly version used is 5.7.18. I updated to 6.1.6 today and now I can clone transactions and also the home tab seems to work well. Thank you very much for the support.
