### ISSUE TITLE
BUG: Chart button crash the app

### ISSUE THREAD

**Issue by MrCaringi** [victorbalssa/abacus#207]
When chart button is used the app crash

**Comment by MrCaringi** [comment]
> @MrCaringi Can you give me some info of your config: Android/iOS, FIII version, any special FIII configuration? Thanks

Hi Victor,

I am using App Version 0.10.2
My iOS version is 17.1.2

I think my FFIII setup is "normal", I am using docker

Debug information generated at 2023-12-05 09:34:50 for Firefly III version **v6.0.30**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.30 / v2.0.11 / 21 (exp. 21)</td></tr><tr><td>PHP version</td><td>8.2.12 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>751, base <span>#</span>40</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Monterrey + America/Mexico_City</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2023-12-04 00:00:00 (1 day ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2023-12-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-12-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0</td></tr></tbody></table>

Let me know if it is possible to export some kind of logs from iOS app

Thanks in advance for your support!

**Comment by victorbalssa** [comment]
Thanks! will try to replicate locally and fix it.

**Comment by MrCaringi** [comment]
Hi!, Any updates?

**Comment by carmo-lucas** [comment]
Same thing happening to me in iOS 17.1.2

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.

**Comment by MrCaringi** [comment]
Hi @victorbalssa 
The issue is still happening in version `0.11.1`

**Comment by victorbalssa** [comment]
Must be something with the first accounts chart then, I will try something else in the next patch: `0.11.2`.

**Comment by victorbalssa** [comment]
@MrCaringi, @carmo-lucas,

With the last OTA update, I created a custom error catching component in the charts view.

Let me know (some screenshots?) if you have more infos on this error.
Thanks

**Comment by MrCaringi** [comment]
Hola @victorbalssa , I hope this helps:

This is the sequence of the video:

1. Open de App
2. It opens in HOME view
3. I change to TRANSACTIONS
4. Go back to HOME
5. Press CHART button
6. It crashed


https://github.com/victorbalssa/abacus/assets/47096567/3ebd3430-6ab9-44e8-9118-2cb500cb36a6

**Comment by victorbalssa** [comment]
Thanks @MrCaringi, did you accept the last Over-The-Air update when launching Abacus in the last 2 days?

If yes, then it's not an account chart error, and I will need to try something else in the next OTA.

If no, can you kill the app and reload it, accept the update and retry?

**Comment by carmo-lucas** [comment]
@victorbalssa 

I reinstalled and now it is working normally, sorry I couldn't offer more information.

**Comment by MrCaringi** [comment]
Hi @victorbalssa 
I just uninstalled the app and try again,

Now it is working!

Thanks for your support!
