### ISSUE TITLE
BUG_Monthly Period is messed up

### ISSUE THREAD

**Issue by Roxas2712** [victorbalssa/abacus#21]
**Describe the bug**
In June Month July is standing as headline. For July August is standing in headline
**To Reproduce**
1. Go to Home
3. Switch to monthly period
4. Take a look to top of the screen 

**Expected behavior**
I would expect that the Intervall of month and the headline are the same.

**Screenshots**
![44733A30-5524-4090-81CD-879809D59D1C](https://user-images.githubusercontent.com/41802861/180382142-078f059c-3053-48a8-b6bc-adae213ad192.jpeg)
![7D780BEC-48D9-41DF-9A8E-07851B870EB0](https://user-images.githubusercontent.com/41802861/180382152-db036f8d-9871-437e-8163-bde3dd334698.jpeg)

**Smartphone (please complete the following information):**
 - Device: IPhone 12 Pro Max
 - OS: 15.5

**Additional context**

**Comment by victorbalssa** [comment]
Thank you for the screenshots,
I think I got something for this one.

Will release it in 0.1.0.

link to #12
