### ISSUE TITLE
BUG_Submitting button don't work

### ISSUE THREAD

**Issue by michelebossa** [victorbalssa/abacus#213]
**Describe the bug**
The button Submitting it is not click able anymore. I have resetted the app but didn't work.

![Screenshot_20231212_183740_Abacus.jpg](https://github.com/victorbalssa/abacus/assets/38975058/2788c35c-236c-4e43-be86-9adde237362f)

**Smartphone 
 - Device: Samsung A52
 - OS: Android 
 - Version 0.10.2

Many thanks for the help

**Comment by michelebossa** [comment]
I have deleted the data of app and relogin again. Now it is fixed but maybe we need some check on code to avoid this strange situation.

Something like every time start new transaction clean data information.

Thanks

**Comment by victorbalssa** [comment]
Thanks @michelebossa, will try to reproduce locally.

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.

**Comment by michelebossa** [comment]
Thanks
