### ISSUE TITLE
Feature Req: Goto today/this month option

### ISSUE THREAD

**Issue by Kage1** [victorbalssa/abacus#216]
**Is your feature request related to a problem? Please describe.**
A few weeks ago I went back in time to view some transactions. Today I opened the app and noticed that I was still 1 year in the past. I can get to current, but requires multiple hops and the app having to pull the transactions for every jump.

**Describe the solution you'd like**
A button, maybe under filter, to goto today/this month.

**Describe alternatives you've considered**
Possibly some type of filter timeout that resets to today/this month, but I could see this being annoying if I didn't want to be on today.

**Additional context**
This possibly could play into a larger feature set to allow picking of a date to view instead of paging back to the month.

**Comment by victorbalssa** [comment]
A click to the current period with a new icon will set you back to today's period.

![Screenshot 2024-01-02 at 12 14 48 PM](https://github.com/victorbalssa/abacus/assets/12813321/35cc127f-1051-4778-9e37-82f2dd4ceefb)
