### ISSUE TITLE
BUG_Android app freezes when logging in

### ISSUE THREAD

**Issue by step0035** [victorbalssa/abacus#223]
**Describe the bug**
I am using cloudflare tunnel + nginx proxy manager for my firefly3 instance. I'm also using personal access token to login to my firefly3 instance from my android device. After inputting the URL and personal access token and logging in, there is a brief moment where i can see "successful connection" or something those lines. Then i got stuck at the abacus logo page.

**To Reproduce**
1. Cloudflare + npm for firefly3
2. Generate personal access token
3. Install abacus from GPS
4. Input firefly3 URL (https://firefly.mydomain.com) and personal access token
5. Login, freezes at logo page.

**Expected behavior**
Should be able to login successfully

**Screenshots**
![freezepage](https://github.com/victorbalssa/abacus/assets/77708985/18465169-4fdc-4442-bed6-1f4772b4c570)

**Smartphone (please complete the following information):**
 - Device: Poco F5
 - OS: MIUI 14 (android 13)
 - Version: MIUI 14.0.7

**Additional context**
-

**Comment by step0035** [comment]
Some updates, i tried to bypass nginx and connect to the firefly3 ip address directly on my lan, still facing the same issue.

**Comment by victorbalssa** [comment]
Hey @step0035,

Unfortunately, I can't reproduce this behaviour locally.

Can you try to connect your phone to the `https://demo.firefly-iii.org/` server? This way we could get more info if it's on the server/network/config side or more on the Abacus app side.

**Comment by step0035** [comment]
Hi @victorbalssa, thanks for looking into this.
I can't reproduce this issue when connecting to the demo firefly server. I have collected the firefly server logs when my phone is trying to connect to it.

```
172.18.0.1 - - [03/Jan/2024:08:12:43 +0800] "GET /api/v1/about/user HTTP/1.1" 200 1250 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/about HTTP/1.1" 200 1030 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/currencies HTTP/1.1" 200 10123 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/insight/expense/category?start=2024-01-01&end=2024-03-31 HTTP/1.1" 200 1555 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/currencies/702/accounts?type=asset&date=2024-03-31 HTTP/1.1" 200 6813 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/budgets?start=2024-01-01&end=2024-03-31 HTTP/1.1" 200 6067 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/summary/basic?start=2024-01-01&end=2024-03-31&currency_code=702 HTTP/1.1" 200 2822 "-" "okhttp/4.9.2"
172.18.0.1 - - [03/Jan/2024:08:12:44 +0800] "GET /api/v1/budget-limits?start=2024-01-01&end=2024-03-31 HTTP/1.1" 200 12471 "-" "okhttp/4.9.2"
```

**Comment by victorbalssa** [comment]
looks like there is an error in the default currency code (you have `702` instead of `USD`, `EUR` etc.).

Which version of FireflyIII are you using? 

If you go to `/currencies` in the web app, can you enable only the used currencies and check if there is only 1 "default" currency?
