### ISSUE TITLE
BUG_foreign currency must be more than zero

### ISSUE THREAD

**Issue by step0035** [victorbalssa/abacus#225]
**Describe the bug**
When adding a transaction, the foreign amount defaults to 0. Upon submitting, error will appear "Value must be more than zero". Workaround is to choose the same currency for the foreign currency and also input the same amount. 

**To Reproduce**
1. Add transaction
2. Fill up the list
3. Hit submit, error "value must be more than zero" will appear due to "0" getting posted for foreign amount.

**Expected behavior**
Don't default to use 0 for foreign amount, leave it blank.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco f5
 - OS: Android 13
 - Version -

**Additional context**
-

**Comment by step0035** [comment]
Btw, found this similar issue on firefly github.
https://github.com/firefly-iii/firefly-iii/issues/8326

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.
