### ISSUE TITLE
unable to add transaction in mobile app

### ISSUE THREAD

**Issue by priyajit4u** [victorbalssa/abacus#226]
There is a error showing value must be greater than 0 and unable to submit the transaction

**Comment by nocturn9x** [comment]
Same here

**Comment by victorbalssa** [comment]
Hey, I'm in the process of deploying the last version with a fix for this 👍🏻

**Comment by victorbalssa** [comment]
#225

**Comment by nocturn9x** [comment]
Great! The app looks awesome, so I'm looking forward to using it :)

**Comment by victorbalssa** [comment]
Version `0.11.1` we be available soon and should fix this bug, let me know if there is still the same error.
