### ISSUE TITLE
BUG_Filter page spills over with all accounts on

### ISSUE THREAD

**Issue by Kage1** [victorbalssa/abacus#227]
**Describe the bug**
On the filter page with the addition of the accounts it now spills off the page and there are no scrollbars to see the rest. The top is also being cutoff.

**To Reproduce**
1. Select all accounts on
2. Click on filter
3. Accounts spill off of the page

**Expected behavior**
Scroll bars to select the various account(s).

**Screenshots**
![AccountOverflow_1.jpg](https://github.com/victorbalssa/abacus/assets/2062390/e8285a26-35bc-434e-ae53-1e7bec58a2fe)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android
 - Version 13

**Additional context**
Also, the accounts are now selectable but selecting one doesn't seem to do anything.

**Comment by victorbalssa** [comment]
Thanks @Kage1!

I forgot that we can have more than 20 accounts. I will add a ScrollView in the next OTA Update: `0.11.2`.

**Comment by victorbalssa** [comment]
Should be fixed in the last OTA, let me know if anything happens.

**Comment by Kage1** [comment]
Just checked, looks good!
