### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by PterX** [victorbalssa/abacus#228]
Hello developer, thank you very much for your project. I am from China and would like to ask if I can help translate it into Chinese.

**Comment by victorbalssa** [comment]
Hey @PterX, we have a translation file for "Chinese Simplified" here: https://github.com/victorbalssa/abacus/blob/updates/src/i18n/locale/translations/zh-CN.ts

If your phone is in `zh-CN` it should show you the translated app, maybe you want a new Chinese version? 

If so you need to create a PR or send me the translation file from EN: https://github.com/victorbalssa/abacus/blob/updates/src/i18n/locale/translations/en-US.ts

**Comment by PterX** [comment]
> Hey @PterX, we have a translation file for "Chinese Simplified" here: https://github.com/victorbalssa/abacus/blob/updates/src/i18n/locale/translations/zh-CN.ts
> 
> If your phone is in `zh-CN` it should show you the translated app, maybe you want a new Chinese version?
> 
> If so you need to create a PR or send me the translation file from EN: https://github.com/victorbalssa/abacus/blob/updates/src/i18n/locale/translations/en-US.ts

Ok, I noticed that this translation is not complete, so it might be a better option for me to submit a PR directly

**Comment by PterX** [comment]
https://github.com/victorbalssa/abacus/pull/231
