### ISSUE TITLE
BUG: Biometric login

### ISSUE THREAD

**Issue by xaiyadev** [victorbalssa/abacus#230]
**Describe the bug**
Biometric login doesnt work.
If used it just reloads to the login page again

**To Reproduce**
1. Open the app
2. Try login with Biometric

**Expected behavior**
Opening the Dashboard

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 1
 - OS: Nothing OS
 - Version 2.0.4

**Comment by victorbalssa** [comment]
@BreakingTV can you login without Biometric correctly?

Are you using the lastest version of FireflyIII?

**Comment by xaiyadev** [comment]
It was the newest Version of firefly...

I fixed it, I dont know how this bug could appear but I needed to create a completly new firefly personal token
After that everything works fine now

Thx anyways :D
