### ISSUE TITLE
BUG_Foreign amount required

### ISSUE THREAD

**Issue by tekjoey** [victorbalssa/abacus#232]
**Describe the bug**
When adding a normal transaction, an error occurs stating "The transactions.0.foreign_amount must be a number". I am then unable to submit the transaction until I put in a value for "Foreign Amount", even if it is zero.

**To Reproduce**
1) Open app and click button to add transaction
2) Fill in all details as normal (Amount, Date, Description, Source/Dest. accounts, etc.)
3) Click Submit
4) Receive error

**Expected behavior**
Submission of transaction without foreign currency requirement.

**Screenshots**
Will add comment with link to video recording

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 17.1.2
 - Abacus Version 0.11.1

**Additional Comments**
My instance of Firefly III does not have any foreign currencies configured (only USD). All of my transactions have always been in USD.

**Comment by victorbalssa** [comment]
Unfortunately it's a side effect of the latest version of FireflyIII.

To address this issue you will need to update to the latest version on you server (currently >= `6.1.6`).

**Comment by tekjoey** [comment]
Thank you for your quick response! I'll update my instance.
