### ISSUE TITLE
BUG_Wrong app theme after system change

### ISSUE THREAD

**Issue by qck4fun** [victorbalssa/abacus#234]
**Describe the bug**
If you have enabled system theme auto-change (day vs. night) and let's say you started Abacus  during the day, then system theme changes to dark and you reopen Abacus, you're still using the same day theme and it looks weird. More in attached pics.

Happens only on Home and Transactions screen.

**To Reproduce**
1. Start app during the day with light system theme
2. Wait until night 
3. Open the app and you'll see the same as I do 

**Expected behavior**
App should sync and follow system theme even if it was initialized with other theme.

**Screenshots**
![image](https://github.com/victorbalssa/abacus/assets/7276555/44d03752-9b21-45b6-aa70-312a66d2cf2e)
![image](https://github.com/victorbalssa/abacus/assets/7276555/17afac91-b2ad-4157-8074-8aa6b2441ffd)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro 
 - OS: iOS 16.6
 - Version 0.11.1

**Additional context**
If you force close and then re-open the app everything is fine. Nothing too much disturbing since there's this workaround.

It was present in previous release as well

**Comment by victorbalssa** [comment]
Should be fixed in the last OTA, let me know if anything happens.

**Comment by qck4fun** [comment]
> Should be fixed in the last OTA, let me know if anything happens.
> 
> 
> 
> 

Will do, thanks 🙏
