### ISSUE TITLE
BUG_Connection view stays minimized after keyboard closed

### ISSUE THREAD

**Issue by shkuviak** [victorbalssa/abacus#236]
**Describe the bug**
When clicking one of the text field on the first connection page, keyboard goes out and view goes all the way up leading to an empty screen.
When hitting return to retract keyboard, the view come back but stays minimized as if the keyboard was still there

**To Reproduce**
1. Open the app for the first time
2. Click one of the text fields
3. View goes braaaap

**Expected behavior**
The view should still be visible when using keyboard

**Screenshots**
1. Click on a text field, keyboard goes out:
![Screenshot_2024-01-13-00-39-04-12_99ee85e1449b867412b241cdd17782b1](https://github.com/victorbalssa/abacus/assets/75165555/d1db5945-b4bd-444f-b276-1f4ffb0d60a9)
2. Hit return:
![Screenshot_2024-01-13-00-32-18-11_99ee85e1449b867412b241cdd17782b1](https://github.com/victorbalssa/abacus/assets/75165555/977388b5-453d-4b33-a63e-3d52b3640e8f)
![Screenshot_2024-01-13-00-32-36-96_99ee85e1449b867412b241cdd17782b1](https://github.com/victorbalssa/abacus/assets/75165555/1448e99b-9837-4127-84e7-6aa366b1c35d)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: OxygenOS
 - Version: 13.1

**Additional context**
Great app budy ! Love nice slick modern UI feeling :)

**Comment by victorbalssa** [comment]
Should be fixed in the last OTA, let me know if anything happens.
