### ISSUE TITLE
BUG_Foreign Amount is mandatory 

### ISSUE THREAD

**Issue by HolGORE** [victorbalssa/abacus#245]
**Describe the bug**
Since the last update the foreign amount of a new transaction is mandatory. I have to set the currency and add a 0 to the amount. There is no * at it and i also didn’t have to set it before the update as far as i remember.

**To Reproduce**
1. Go to 'new transaction’
2. Fill out all mandatory fields
3. Send the transaction
4. See error “transactions.0.foreign_amount must be a number’

**Expected behavior**
Foreign amount shouldn’t be a mandatory field in my option, since there is no *
Or is it only me and there an issue on my side?

**Screenshots**
![IMG_4447](https://github.com/victorbalssa/abacus/assets/5708389/d1fe5a65-7681-40fe-b538-b55087b28f1d)
![IMG_4448](https://github.com/victorbalssa/abacus/assets/5708389/aed99d50-c95b-4a38-9917-907134f7edf6)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 17.2.1
 - Version 0.11.1

**Additional context**

**Comment by victorbalssa** [comment]
Hi @HolGORE,
I'm working on Abacus to support only the latest version of FireflyIII. 
Unfortunately, this bug was "server side", could you update your FireflyIII instance to the latest version? It should fix it 👍🏻 

Thanks!

**Comment by victorbalssa** [comment]
linked to #225 and #232
