### ISSUE TITLE
Bug: Transactions created by Abacus for iOS do not appear in the app

### ISSUE THREAD

**Issue by TickDracy** [victorbalssa/abacus#252]
**Describe the bug**
When a transaction is created within the latest Abacus version for iOS (0.12.4), it doesn't appear on the list of transactions. But if the transactions were created on the server or on a previous version of Abacus, it shows up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Abacus app and click the **+** to add a new transaction.
2. Fill all the required fields.
3. Submit the transaction.
4. Go into the transactions. The new, created one, is not there.
5. On the server, you can see the transaction created by Abacus. **Edit** the transaction with anything.
6. The _edited_ transaction will now appear on Abacus.

**Expected behaviour**
The transaction created by Abacus should appear on the list of all transactions, without needing to go into the server and edit it.

**Smartphone:**
 - Device: iPhone 11 Pro
 - OS: iOS 17.3.1
 - Version 0.12.4

**Comment by victorbalssa** [comment]
Hey @TickDracy

I will need more information:
- was the transaction date in the future? -> Transactions Search only show transactions before today +1d (today included) but I will add a period switcher in the future
- was the transaction date today? -> might be a diff with the server datetime and your phone datetime

If you try to create a transaction with the date set to yesterday, can you see it?

> it doesn't appear on the list of transactions.

Even if you refresh the transaction search without any filters?

**Comment by TickDracy** [comment]
Hi @victorbalssa,

> was the transaction date in the future? 

No! In fact, I never noticed that we could add a transaction within the future. All the ones I add on the app are in the _present_ or in the _past_.

> was the transaction date today?

Yes, the transaction was on the present time (of when I added it).

> Even if you refresh the transaction search without any filters?

Yes, refreshing, or _cleaning and restarting_ the app doesn't make a difference.

> If you try to create a transaction with the date set to yesterday, can you see it?

I tried right now, and yes, it shows if I set it to yesterday. But if I do a transaction for 4 or 5 hours in the past, it doesn't show up.


But now I noticed a pattern: All transactions submitted through the app, do not have the hour that I set in the input box correct, they are one hour ahead (e.g. I added the timestamp 16:30 on the app, but on the server it was 17:30).

The hour is correct on the phone, and it's the same as the one on the server, which is WET (UTC+0).

Please let me know if you need additional information.

**Comment by victorbalssa** [comment]
Thank you @TickDracy, it will be fixed in the next `0.13.0` release.
(set the `date_before` to +1months)

**Comment by TickDracy** [comment]
Hi @victorbalssa, the 0.13.2 version released on the AppStore, completely broke the app for me. Any transaction returns a 422 error.
Is it possible to revert it back?

**Comment by victorbalssa** [comment]
Hey @TickDracy, 422 error happen when there is a format issue with the transaction: following here: https://github.com/victorbalssa/abacus/issues/265
