### ISSUE TITLE
After creating a transaction, you need to slide to the bottom to submit. It is recommended to place the submit button in the top right corner and the cancel button in the top left corner.

### ISSUE THREAD

**Issue by s4w4j4** [victorbalssa/abacus#254]
After creating a transaction, you need to slide to the bottom to submit. It is recommended to place the submit button in the top right corner and the cancel button in the top left corner.
![image](https://github.com/victorbalssa/abacus/assets/90949008/d324db42-cea1-4a87-b388-d8ba467efcb6)

**Comment by SimonAkers** [comment]
Alternatively, a floating action button could be added to the bottom right corner of the screen. This is far easier to reach with a thumb than the top corner, and is common practice in many mobile apps.

**Comment by victorbalssa** [comment]
Done in `0.13.2`
