### ISSUE TITLE
Feature Request: Select bill for transaction

### ISSUE THREAD

**Issue by SimonAkers** [victorbalssa/abacus#255]
**Is your feature request related to a problem? Please describe.**
I am trying to create transactions for bills that don't have an automated rule to associate them, but as bill selection is not an option, I have to resort to the FF3 web interface to track my bill payments.

**Describe the solution you'd like**
A searchable drop-down that shows the list of existing bills and allows you to select which one the transaction is for.

**Describe alternatives you've considered**
Alternatives include creating rules to handle bill association, or using the FF3 web interface to track bill payments. However, I prefer to select the bill manually, and to use this app!

**Additional context**
This feature request is primarily for my significant other, who is not a technical user and does not want to learn about FF3 automation. For now she is using fixed budgets in place of bills, so that she can still use this app and not have to mess with the more complex web interface. I myself would also prefer to select a bill when creating a transaction for one, just for the peace of mind that it was manually selected.

**Comment by victorbalssa** [comment]
ToDo #239 before this one.
