### ISSUE TITLE
Bug: Unable to authenticate/Crash on login

### ISSUE THREAD

**Issue by Fred-Oco** [victorbalssa/abacus#257]
**Describe the bug**
After filling in the credential, the app present a black screen. Once stop the app, re-login crash the app. 

**To Reproduce**
1. Fill in the http://ip:port (connected with openvpn server hosted on nas)
2. Click on submit
3. Web page ask for authentication
4. Click authenticate
5. "Submitting" on the button
6. Black screen
7. kill the process
8. Re-open, click on the saved credentials
9. Crash

**Expected behavior**
Home page after submitting credential

**Screenshots**
Can provide if needed, since it is just a black screen...

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.3.1
 - Version: 0.12.4

**Additional context**
"GET /oauth/authorize" request return 302 from the server log.
I've found similar issues mentioned, but no more detail from that post.

Happy to provide more detail if needed. Looking forward to try the app. Thanks

**Comment by victorbalssa** [comment]
Thank you @Fred-Oco I definitely need to fix this.
Can you try to connect to this demo instance: https://demo.firefly-iii.org/ ?
it will help me determine if it's really the network config or something else.

**Comment by Fred-Oco** [comment]
I've tried using personal access token and OAuth
![image](https://github.com/victorbalssa/abacus/assets/69133888/69cd65d5-8931-42ca-9a69-c4944ad40e6b)
OAuth gave this

For personal token, it failed to validate the token and asked for re-check.

**Comment by victorbalssa** [comment]
I just tried with both PAT and OAuth flow and it's working on my end 🤔 
Do you have the same config for OAuth:
![image](https://github.com/victorbalssa/abacus/assets/12813321/111c527a-fae3-4bd5-bd4e-7dedc8246cf9)


In any case it should work for PAT...

**Comment by Fred-Oco** [comment]
I tried few time with a different phone, same problem. Even changing network/closing openvpn gave the same result regarding connecting to the demo server or my personal one.

**Comment by victorbalssa** [comment]
Can you share with me your FireflyIII version? is it the last `6.1.9`?

**Comment by Fred-Oco** [comment]
Yes. It is the latest version.

**Comment by victorbalssa** [comment]
Done in `0.13.2`.
Let me know if there is still an issue with this.

**Comment by Fred-Oco** [comment]
Same problem.
With my own account it gave a black screen.
When I try the demo, PAT gave error 403.

**Comment by phuchoang2603** [comment]
Hello
I also have the same issue on my Iphone 7 (ios 15.7). Both firefly and abacus latest version
Using personal access token and cloudflare tunnel.
It seems that I was able to login the app but it just appears black.

![RPReplay_Final1718012888](https://github.com/victorbalssa/abacus/assets/91061595/57d6ef8a-bddb-4e74-a3bc-0bfb05e494ee)

**Comment by D4rkT1m0** [comment]
hello guys, same issue here, is there any news?
iOS: 16.7.8
abacus: 0.16.0
firefly: 6.1.18
auth: PAT

when I open the app, it keeps asking me to update.
if i select the update, the screen goes black. I have do uninstall the app from my phone and reinstall it to make it accessible again.
if I select later, seems to work fine
I don't understand why the app ask to update, I'm in the latest abacus version.


I recently renew my ssl certificate for my reverse proxy, is there a chance that the issue is linked?

**Comment by phuchoang2603** [comment]
@victorbalssa  Despite the latest update, I am still unable to log in to the app. Could you investigate the issue, as I have noticed several users are experiencing the same problem?

**Comment by victorbalssa** [comment]
@D4rkT1m0 @phuchoang2603 @Fred-Oco 

Do you have the same issues with https://demo.firefly-iii.org & Abacus `0.18.0`?

Thanks!

**Comment by phuchoang2603** [comment]
yeah same with @Fred-Oco, when i tried the demo instance, i got the 403 error![image](https://github.com/victorbalssa/abacus/assets/91061595/c184bcd8-6a57-48dc-8264-55b4b364118d)

**Comment by D4rkT1m0** [comment]
Since I update in 0.18.0 I am unable to connect anymore. 
Screen stays black, event if I uninstall completely the app from my iPhone.

**Comment by victorbalssa** [comment]
New fix available on OTA update.

Following this issue in #311.
