### ISSUE TITLE
Bug: "Request failed with status 422"

### ISSUE THREAD

**Issue by gittbuh** [victorbalssa/abacus#258]
**Describe the bug**
Whenever a submit a withdrawal I get a red error box with the error message "Request failed with status 422".

**To Reproduce**

**Expected behavior**
No error messages when submitting a withdrawal.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel6a and iPhone 8
 - OS: Android 14 latest version and iOS 16.7.5

**Additional context**
Tried with both oauth clients and personal access token authentication.

**Comment by victorbalssa** [comment]
Following in #259

**Comment by TickDracy** [comment]
@victorbalssa I'm having the same issue (but only after the update released yesterday). According to the https://github.com/victorbalssa/abacus/issues/259 the solution is to upgrade the Firefly installation, but I'm unable to do it (because the hosting doesn't allow me to).

Is there any way for me to use an older version of the app, which was working perfectly fine for me?

**Comment by victorbalssa** [comment]
following https://github.com/victorbalssa/abacus/issues/265.

I will just, try to display the current formatting error.
But my guess is that the Foreign currency should be set to zero each time you create a new currency.
I created a new switch btn a the end of the transaction form to allow you to display/hide the foreign currency field.

**Comment by victorbalssa** [comment]
> but I'm unable to do it (because the hosting doesn't allow me to)

this is the bug you might have with an older F3 version https://github.com/firefly-iii/firefly-iii/issues/8326

**Comment by TickDracy** [comment]
@victorbalssa Thank you! I've sorted the issue with my hosting provider, and I was able to upgrade the Firefly instance into the latest version. The app is now working as expected.

Cheers!
