### ISSUE TITLE
Bug: "The transactions.0.foreign_amount must be a number" error when there is no foreign amount

### ISSUE THREAD

**Issue by gittbuh** [victorbalssa/abacus#259]
**Describe the bug**
Whenever I submit a withdrawal in EUR in both source and destination accounts in EUR, I get a red box error message saying "The transactions.0.foreign_amount must be a number". So I am basically forced to input twice the amount I am withdrawing. However, this Foreign amount box is not mandatory or it should not be when there is no foreign amount at all.

**To Reproduce**

**Expected behavior**
Not be forced to enter twice the amount to be withdrawn in same currency.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6a and iPhone 8.
 - OS: Android 14 latest version and iOS 16.7.5.

**Additional context**

**Comment by victorbalssa** [comment]
Hey @gittbuh,
linked to #245, #225, #232, #258

This should be that your FireflyIII instance version is outdated, please upgrade to the latest version https://github.com/firefly-iii/firefly-iii/releases/tag/v6.1.9.

Thank you,
Victor
