### ISSUE TITLE
FR: Any transaction returns a 422 error. specify the error message in transaction from

### ISSUE THREAD

**Issue by victorbalssa** [victorbalssa/abacus#265]
**Describe the bug**
Any transaction returns a 422 error. specify the error message in transaction from.

follow: https://github.com/victorbalssa/abacus/issues/252

https://github.com/victorbalssa/abacus/issues/252#issuecomment-1991805955

**Comment by Zackyist** [comment]
I am getting this error on Android after updating the app to the latest version, completely clearing the app cache and storage and logging in. If I try to add a transaction, it always fails with this error - regardless of the transaction type or details.

I only fill in the required fields. I have tried changing the description, the amount (with and without decimals), the source account, the destination account, both accounts as well as tried Withdraw, Deposit and Transfer. After checking the linked issue I also tried setting the time to 4 hours before present, yesterday as well as 6 days ago. Nothing worked and I always get 422.
