### ISSUE TITLE
Bug: Cant relogin after changing phone

### ISSUE THREAD

**Issue by michelebossa** [victorbalssa/abacus#266]
**Describe the bug**
I'm retrying to re login into app but didn't work i'm sure the url and the token it is ok because if i change some digit i receive a different error.

Can you check?
Thanks

**Screenshots**
<img width="193" alt="image" src="https://github.com/victorbalssa/abacus/assets/38975058/4fbaa018-8217-44fa-9632-ee42bc26fced">

**Smartphone (please complete the following information):**
 - Device: Samsung A54
 - OS: Android
 - Version 14

**Comment by victorbalssa** [comment]
Looks like it is an issue on android with Expo (https://expo.canny.io/feature-requests/p/securestore-fix-could-not-decrypt-the-item-in-securestore).

Can you delete and reinstall the app?
Did you change your device recently?
Thx

**Comment by michelebossa** [comment]
Hi,
Yes i have changed the phone and delete and reinstall again the app the problem persist but i tryed to delete cache and data and it is work.

i'm closing the issue many thanks.
