### ISSUE TITLE
Bug: Getting "Request failed with status code 422" while creating a multi-currency transfer

### ISSUE THREAD

**Issue by ikotamsl** [victorbalssa/abacus#272]
**Describe the bug**
Getting an error while making a transfer transaction that requires two currencies (basically currency exchange)

**To Reproduce**
1. Go to 'Home Screen'
2. Click on '+ (New Transaction)'
3. Scroll down to 'Foreign Currency' switch
4. Enable 'Foreign Currency' switch
5. Scroll up
6. Enter a number in 'Amount' field
7. Enter a number in 'Foreign currency' field
8. Fill 'Description' field
9. Choose a source account with currency A
10. Choose a destination account with currency B
11. Press 'Submit'
12. See error 'Something went wrong - Request failed with status code 422'

**Expected behavior**
A transfer transaction is created

**Screenshots**
![IMG_0024CE29EAB7-1](https://github.com/victorbalssa/abacus/assets/51887576/8072eccb-cf1f-4a8b-83f9-203448df1691)
![IMG_A988AB44A2C4-1](https://github.com/victorbalssa/abacus/assets/51887576/6c632dfb-40f0-444a-8c3f-51065221e690)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 17.4.1
 - Version 0.13.2

**Additional context**
The transfer transaction, that transfers money between accounts with one currency is created correctly. The foreign currency functionality works perfectly in Firebase III web interface.

**Comment by ikotamsl** [comment]
Addition to context: I am choosing a date in past, so there is no problem with that

**Comment by victorbalssa** [comment]
Hey @ikotamsl,

It's not very easy to read but you need to select a Foreign Currency by clicking on `Foreign currency` left of the 30000 on your screenshot.

**Comment by ikotamsl** [comment]
Oh, I didn't actually know about this) Maybe it is possible to automatically choose the foreign currency by the currency of the destination account? Or at least make the button more obvious&

Anyway, all works now and I'm satisfied)

**Comment by victorbalssa** [comment]
Cool, with #265 it should be easier to read the error message instead of "422 Error".
I'll close it for now.
