### ISSUE TITLE
Bug: ios app keeps sliding from left to right

### ISSUE THREAD

**Issue by bushvin** [victorbalssa/abacus#279]
**Describe the bug**
When launching the app after authenticating (both oauth and token) to my personal instance, the app seems to go in a loop where the app screen slides from left to right. There is no way stopping the app, except by swiping it up in the task list.

**To Reproduce**
1. Add credentials (token based or oauth)
2. Select credentials or start app

**Expected behavior**
Probably a welcome screen

**Screenshots**
I'll try to upload a video

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 17.4.1
 - Version [e.g. 0.11.0]

**Additional**
N/A

**Comment by victorbalssa** [comment]
Hey @bushvin, is it the same as https://github.com/victorbalssa/abacus/issues/270#issuecomment-2089346456 ?

I'm working on it 👌🏻

**Comment by bushvin** [comment]
It does indeed seem to be the case.

I will close this issue in favour of #270

Thank you for your prompt response!
