### ISSUE TITLE
Bug: App flashing on Galaxy Fold 4

### ISSUE THREAD

**Issue by rickyi89** [victorbalssa/abacus#280]
Hi, I just installed the app on my Galaxy Fold 4 and after logging in with the personal access token the app starts flashing without control. This happens on both external and internal screen. Attached a short video to explain. The interface seems to be working though. 

https://github.com/victorbalssa/abacus/assets/10656536/3504b2b5-4d73-4b04-9330-a0f0e952218e

**Comment by victorbalssa** [comment]
Hey @rickyi89, It should be the same error as #270, I'll working on something stable and will deploy it in the next patch.

**Comment by victorbalssa** [comment]
duplicated #270
