### ISSUE TITLE
Lower toolbar overlaps with main settings screen 

### ISSUE THREAD

**Issue by sebashepin** [victorbalssa/abacus#29]
**Describe the bug**
On the settings screen, the lower toolbar overlaps with the main screen. Hides the debug row

**To Reproduce**
1. Go to settings screen
2. See error

**Expected behavior**
The main screen is fully visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1766748/183779438-a7a2c224-ea05-473b-bf5b-fe8b7136f34e.png)

**Smartphone:**
 - Device: iPhone SE (1st generation)
 - OS: iOS 15.6
 - Version: 0.21 BETA

**Comment by victorbalssa** [comment]
Hey @sebashepin, 
Thanks for the feedback,

will release 0.2.2 shortly.

**Comment by victorbalssa** [comment]
Can you retry with 0.2.2 version?

**Comment by sebashepin** [comment]
Confirmed as fixed, thank you mate
