### ISSUE TITLE
App not available on the app store

### ISSUE THREAD

**Issue by Marcio2536** [victorbalssa/abacus#301]
When I clicked on the link of the abacus app, it simply shows "This app is not available" message on App Store. Is there any issues with the app itself?
![image](https://github.com/victorbalssa/abacus/assets/61924136/60eb5c6f-c3e3-4069-8c9f-f7e18f4489aa)

**Comment by Drudoo** [comment]
I'm having the exact same issue on multiple different countries appstores.

**Comment by shantheone** [comment]
I can confirm the same, I installed the app a few weeks ago without issues and now it's gone.

**Comment by victorbalssa** [comment]
It's back now, it was an issue with my Apple dev account.
