### ISSUE TITLE
Bug: Resource not found error poped up on Home Screen after upgraded to v0.16.0

### ISSUE THREAD

**Issue by EvanNotFound** [victorbalssa/abacus#302]
**Describe the bug**
Every time I open up the app in the home page, the asset account will not show up, at the same time, the notice "Transaction created" and "Resource not found" will pop up. Only the home page has this error, everything else works fine (adding transactions etc). I have already tried to relogin / reinstall, didn't help.

**To Reproduce**
1. Open the app Home Screen.
2. See error popped up and assets accounts didn't show up.

**Expected behavior**
No error popups and assets account shows correctly.

**Screenshots**
![image](https://github.com/victorbalssa/abacus/assets/68590232/a0d23093-5850-4edc-abda-22e504d177a2)

![image](https://github.com/victorbalssa/abacus/assets/68590232/99fb8b5a-1b78-4125-bad1-68b02e14e4de)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 17
 - Version 0.16.0

**Comment by victorbalssa** [comment]
Hey @EvanNotFound, do you have access to the FIII backend logs? what's your FIII version?

**Comment by EvanNotFound** [comment]
Hi!

After updating Firefly III to the lastest version, the problem is solved. Thanks for your help!
