### ISSUE TITLE
Bug: Transaction created by web-based FF3 show incorrect value in Abacus

### ISSUE THREAD

**Issue by igneous80** [victorbalssa/abacus#304]
**Describe the bug**
The time value of transactions create by web-based FF3 seems to show incorrect value in Abacus.

**To Reproduce**
1. Create any transaction using Web-based FF3
2. Go to Abacus transaction menu
3. Click on any transaction created by web-based

**Expected behavior**
- show the correct time value as in web-based FF3

**Screenshots**
![1](https://github.com/victorbalssa/abacus/assets/61380528/78bb15a5-15c8-44e2-81d9-2218ad8bec9c)
![2](https://github.com/victorbalssa/abacus/assets/61380528/8ac3d811-d709-4fb7-bf55-917cf193c08a)

**Smartphone (please complete the following information):**
 - Device: [Huawei P30]
 - OS: [EMUI 12.0.0]
 - Version [e.g. 0.16.0]

**Additional context**
- If transaction created by Abacus itself it show correct time value both in app and web-based
- Another app (waterfly III) show the correct value.

**Comment by victorbalssa** [comment]
It's something related to the FIII timezone config: https://github.com/firefly-iii/firefly-iii/blob/main/.env.example#L34

**Comment by igneous80** [comment]
It works as expected, Thank !
