### ISSUE TITLE
Bug: Setting Button "Close the transaction form after submission" Not completely visible

### ISSUE THREAD

**Issue by databloat** [victorbalssa/abacus#313]
**Describe the bug**
Just a small optical error.
In the settings tab, the activate/deactivate button of the option "Close the transaction form after submission" is not completely visible, but half disappears.

**To Reproduce**
1. Go to 'Settings'
2. Scroll down to Option 'Close the transaction form after submission'

**Screenshots**
![IMG_20240708_235422](https://github.com/victorbalssa/abacus/assets/47503335/b6ac8cd5-83c4-4ca2-8e26-c346e2e36852)

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - OS: Android

Many thanks for this great app, very well done.

**Comment by hamza-fadil** [comment]
String is a bit long, should we reduce font size, reduce string length or add a line break @victorbalssa ?

**Comment by marcelweikum** [comment]
Hey, this is already fixed in the new PR #320 commit d2645312251b182726edd9f48b9163898db304c1
