### ISSUE TITLE
Bug: iOS v 0.18.0 opens up to black screen.

### ISSUE THREAD

**Issue by drewzeee** [victorbalssa/abacus#314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 15]
 - OS: [e.g. iOS 17]
 - Version [e.g. 0.11.0]

**Additional context**

**Comment by victorbalssa** [comment]
following in #311 👌🏻
