### ISSUE TITLE
Bug: Filters are not filtering for Asset Accounts

### ISSUE THREAD

**Issue by marcelweikum** [victorbalssa/abacus#322]
**Describe the bug**
The Asset Account Filters you can add in any of the Screens don't work. All Accounts are still displayed.

**To Reproduce**
1. Create multiple Asset Accounts
2. Filter for specific Accounts
3. Still see all Accounts displayed

**Expected behavior**
When I Filter for Asset Accounts, there should only be the ones displayed, which I selected. On the HomeScreen, Graph and Transactions

**Screenshots**

![image](https://github.com/user-attachments/assets/c1cfad3d-fccb-4105-beea-12de9a6e9828)

![image](https://github.com/user-attachments/assets/6417cc22-5831-4d75-8bc1-45d87956f11d)

![image](https://github.com/user-attachments/assets/8f08af8c-c1e7-4dfe-b815-a217022f833b)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 18.3
 - Version 0.18.0

**Comment by victorbalssa** [comment]
I definitely need to remove these filters from home screen, it's only for the chart screen I will add it to my ToDo.

**Comment by marcelweikum** [comment]
> I definitely need to remove these filters from home screen, it's only for the chart screen I will add it to my ToDo.

I've tested this a bit:

If you have multiple accounts with different currencies, the filters work just fine on the HomeScreen as well as on transactions, regarding the "Currency" filter. However, if the filters are removed, I don't think there would be a way to check different currency accounts. Handling multiple currencies is also something that the original Firefly-III doesn't manage well in summary...

So maybe remove filters but add an option for switching to different currency accounts.
