### ISSUE TITLE
Feature Request: Can you provide an APK file or download link?

### ISSUE THREAD

**Issue by 616734202** [victorbalssa/abacus#326]
Hello, I am in China and the Android phone I use does not have the Google Framework. I cannot download apps from the Google Play Store. Can you provide an APK file? It is also recommended that you store it in Releases for devices that do not have the Google Framework to download and install.

**Comment by victorbalssa** [comment]
Hey ready to download here: https://github.com/victorbalssa/abacus/releases/tag/0.20.0
