### ISSUE TITLE
Bug: Cannot Login with saved Credentials

### ISSUE THREAD

**Issue by vspaziani** [victorbalssa/abacus#332]
When I have saved credentials using the OAUTH client ID and Client Secret, I receive an error after the credentials are some period of old. I am currently running another test to see what that time frame is, but thought I would ask if you have seen this before or know how I can troubleshoot. I am on IOS OS.

**To Reproduce**
1. Login and save credentials using OAUTH client ID and Client Secret
2. Use app as normal
3. after some time period (to be determined), when you open the app again you are presented with a login screen with your saved credentials
4. when you click on the saved credential, nothing happens.
5. (on the server side) I see an error :

> "[03/Sep/2024:21:25:19 -0600] "POST /oauth/token HTTP/1.1" 500 1938 "-" "Abacus/0.20.0 CFNetwork/1498.700.2 Darwin/23.6.0"

I suspect that the token that I had has expired. Just a guess since I can use the application without issue for an extended timeframe.

**Expected behavior**
If token is expired, I expect a message to refresh credentials. If token is not expired and some other issue, a message detailing issue would be very helpful.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro 
 - OS: IOS 17.6.1 (though it has persisted for many versions)
 - Version 0.20.0 though it has been an issue for previous versions, latest updates at least allow me to delete old credentials now.

**Additional context**
if there are additional items that I can try or something I am open to that. I can clone the VM and troubleshoot.

**Comment by victorbalssa** [comment]
(for Oauth2) all refresh token should work as expected (refreshing new access token if possible).

Sometimes we need a new token when it's not possible, we can remove the credential and create a new one in Credential screen.

Let me know if this is still an issue with version 0.20.1 and we can re-open this ticket.
