### ISSUE TITLE
Asset accounts don’t update on refresh

### ISSUE THREAD

**Issue by whacky3112** [victorbalssa/abacus#336]
I have been making transactions in my asset accounts but they aren’t reflected in the Abacus app. The account totals are reflected correctly when I access it from the browser

**Comment by victorbalssa** [comment]
Hey @whacky3112, do you have filters applied?

**Comment by whacky3112** [comment]
No filters are applied. Still it doesn’t update the individual asset accounts. Total net worth gets updated. Any transactions entered are registered correctly in the database. I know the app is at version 0.20. But this was just to improve the quality of the app at a faster pace. Thank you. Sent from my iPhoneOn 3 Oct 2024, at 3:38 AM, Victor Balssa ***@***.***> wrote:﻿
Hey @whacky3112, do you have filters applied?

**Comment by victorbalssa** [comment]
There is a default filter in Transaction tab to the start of current period, can you double check removing this filter solves your issue?

**Comment by whacky3112** [comment]
Shall try Sent from my iPhoneOn 6 Oct 2024, at 4:23 AM, Victor Balssa ***@***.***> wrote:﻿
There is a default filter in Transaction tab to the start of current period, can you double check removing this filter solves your issue?
