### ISSUE TITLE
BUG_Crash_on_incomplete_URL

### ISSUE THREAD

**Issue by Rbn3c** [victorbalssa/abacus#34]
**Describe the bug**

When entering the firefly address without http(s) the app crashes without error when continuing.

**To Reproduce**

1. Start freshly installed app.
2. Enter address without http(s):// e.g. firefly.domain.com

**Expected behavior**

Request to fix address, auto adding of http(s).

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 13 pro
 - OS: [e.g. iOS8.1] 15.6
 - Version [e.g. 22] 0.2.2

**Additional context**

**Comment by victorbalssa** [comment]
Hey @Rbn3c ,
Thanks for the feedback,

Quick fix: `BackendURL` regex force you to start with `http|https`.

Released in #36.
