### ISSUE TITLE
Bug: no transactions displayed

### ISSUE THREAD

**Issue by minusmaster** [victorbalssa/abacus#343]
**Describe the bug**
no transactions are showing since I split one. The display is ok on the online version, then it's an application problem 

**To Reproduce**
Split a transaction and go to the transaction display

**Expected behavior**
All the transactions have to be displayed.

**Smartphone (please complete the following information):**
 - Device: pixel 6a
 - OS: Android 14
![Screenshot_20241015-124516](https://github.com/user-attachments/assets/244c6e80-3e17-4ce1-be85-aec2eec4cb1b)

**Comment by victorbalssa** [comment]
Hi @minusmaster, There is a default filter set "1 oct. 2025" that follows current "Home" filter
