### ISSUE TITLE
Feature Request: Search for "Descriptions" of Transactions

### ISSUE THREAD

**Issue by n00b12345** [victorbalssa/abacus#344]
**Is your feature request related to a problem? Please describe.**
The inability search for "Description" within transactions is an annoyance. Without this feature, searching for a transaction that is older than a year for categories that I use frequently, is practically impossible.

**Describe the solution you'd like**
In the Transactions tab, I should be able to search for Descriptions of transactions.

**Describe alternatives you've considered**
There is no alternative solution other than going to Firefly web and checking the details.

**Additional context**
None.

Thank you for making Abacus. It's wonderful.

**Comment by victorbalssa** [comment]
![image](https://github.com/user-attachments/assets/0fdb40b7-0375-4e38-9973-2a07e8327dfb)

When you check the transactions tab and scroll down a bit you will be able to find the search box for description 👍🏻

**Comment by n00b12345** [comment]
> ![image](https://github.com/user-attachments/assets/0fdb40b7-0375-4e38-9973-2a07e8327dfb)
> 
> When you check the transactions tab and scroll down a bit you will be able to find the search box for description 👍🏻

Thank you so much for clarifying. Really appreciate your help. I can now narrow down the transaction.

Is there any way to do a search for Categories? That would further help to streamline the search. 

Thank you again.

**Comment by victorbalssa** [comment]
> Is there any way to do a search for Categories? That would further help to streamline the search.

It's in my todo 👌🏻
