### ISSUE TITLE
Feature Request: Net Worth charts improvement

### ISSUE THREAD

**Issue by joluas** [victorbalssa/abacus#347]
**Is your feature request related to a problem? Please describe.**
The net worth charts are displayed as follows on the app:
![WhatsApp Bild 2024-11-04 um 19 18 02_cb384753](https://github.com/user-attachments/assets/483d020a-7221-488c-8b7c-63b00207dd5a)
![WhatsApp Bild 2024-11-04 um 19 18 02_0fbed77e](https://github.com/user-attachments/assets/31344f10-da67-407b-8b41-58027ac14996)

Even when information is being transmitted, it is not using the screen on a way that could convey more information.

**Describe the solution you'd like**
Net worth could be displayed differently like this:
![image](https://github.com/user-attachments/assets/6966d7b8-2c9d-402e-ab98-6c91d9c2263e)

Or something like this:
![image](https://github.com/user-attachments/assets/c92d5fff-4c14-4a37-8895-040383975d61)

**Describe alternatives you've considered**
The real state of the screen is not used to its fullest potential. A way of being able to see its progress with a graph is ideal. I have considered candlestick charts or line charts as the best approach and during the current month progression chart could be updated so that you can go back months and see how the net worth changed during previous or current month

**Additional context**
No additional context

**Comment by victorbalssa** [comment]
Good idea! Unfortunately for monthly period it's a bit empty, try the yearly period and it should make more sense 👍🏻

**Comment by joluas** [comment]
Hello @victorbalssa,

Thanks for pointing that out. I see now that I have to switch to 3M, 6M or 12M in order to see more info in the graphics. 

Great app!
