### ISSUE TITLE
BUG_Crash_at_transactions_menu (0.2.3)

### ISSUE THREAD

**Issue by danielnbalasoiu** [victorbalssa/abacus#37]
**Describe the bug**
The app crashes when Transactions menu is opened. (version `0.2.3`)

**To Reproduce**
1. Open app
2. Click on Transactions menu (the icon before settings icon)
3. App crashes

**Expected behavior**
Transactions history should be displayed.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Version `15.6.1`

**Additional context**
I have tested version `0.2.2` on another phone (same model, iOS version is `15.6.0`) and it works fine.

**Comment by victorbalssa** [comment]
Thanks @danielnbalasoiu!
Did not catch this one, it was due to old rematch cache.

Can you restart your app (version 0.2.3), accept update and retry the Transaction list?

**Comment by danielnbalasoiu** [comment]
I forgot to mention. I have restarted the app and also cleaned the cache and reconfigured Firefly-III server.

**Comment by danielnbalasoiu** [comment]
I cleaned Safari cache and it worked. After that the app displayed a pop-up to notify an update is available and then all went fine. 👏 

Thank you!

Keep up the great work you're doing! 🚀

**Comment by danielnbalasoiu** [comment]
This behavious is repeating. :(
I cleared Safari's cache, reseted Abacus app a couple of times but the app keeps crashing on Transactions menu.

I haven't made any change on my side. Neither on the server side, nor on the phone/application.

**Comment by danielnbalasoiu** [comment]
I have a screen recording. Can you share your email address to sent it to you?

**Comment by victorbalssa** [comment]
Hello @danielnbalasoiu,
Yes you can: contact@victorbalssa.ca

Is it still the same when re-installing the app from AppStore?
What's your Firefly III version?

**Comment by danielnbalasoiu** [comment]
Yes, I have reinstalled the app, made sure Safari's cache is gone and even rebooted the phone.

Firefly III Version: `[5.7.10]`

**Comment by victorbalssa** [comment]
@danielnbalasoiu I think I got the fix,
It could be related one type of transaction not handled yet.

Could you update the last fix and retry please?

**Comment by danielnbalasoiu** [comment]
Yup, it's fixed. 👏
