### ISSUE TITLE
BUG_Icons on navbar not appearing when using other language beyond English

### ISSUE THREAD

**Issue by carvalholeo** [victorbalssa/abacus#63]
**Describe the bug**
All icons (except the pencil and transactions) don't appear when you use a different language in the system. So, the interface could be broken for non-English iDevices users.

**To Reproduce**
1. Go to 'Settings' app on the system. So, enter into 'General' section. After, 'Language & Region'
2. On 'Preferred Languages,' tap to 'Add Language' and select one of the supported languages at the app (e.g, 'Portuguese (Brazil)' or French). So, put as preferred language.
3. Allow to iPhone restart device with new language
4. Open Abacus to see navbar without almost any icons
5. Repeat steps 1-4, changing language back to English, to see all icons back.

**Expected behavior**
As a non-English user of the app, I expect that icons must appear, to guide me and myself experience across the app on how to use.

**Screenshots**
Navigation bar when using in Portuguese
![IMG_4005](https://user-images.githubusercontent.com/19316339/209693906-da39a393-4b38-4ce9-8668-b9d502dab6f5.PNG)

Navigation bar when using in English
![IMG_4006](https://user-images.githubusercontent.com/19316339/209693956-67eb75cf-2344-4cec-b917-ce0f0b5b7808.PNG)

**Smartphone:**
 - Device: iPhone12
 - OS: iOS 16.1.2
 - Version 0.4.0

**Additional context**
Probably this bug it was generated by me. It occurs because on routes screen, the object for icons expect receive for a name in English. While the app didn't translate, this wasn't a problem.

But, when I made the last PR (#48), I introduced this bug for translating navigation bar names, that were used to access object with icons names. Sorry for this.

I'm working right now at a bugfix for this. I'm sorry for neither report nor see this bug before, I don't have an Apple setup (any Mac, it's too much expensive in Brazil) to debug iOS apps.

Likewise, I believe that between today and Friday, I'm going to open a new PR, solving this bug.

**Comment by victorbalssa** [comment]
will be fixed in next update.

**Comment by victorbalssa** [comment]
@carvalholeo should be fixed.
