### ISSUE TITLE
Feature Request: Add transaction splits to Transaction Form & Transaction View

### ISSUE THREAD

**Issue by elissonsilva85** [victorbalssa/abacus#73]
When a record has subitems the app is showing only the first subitem title and value. The correct one should show the title of the grouped subitems and the sum of all values inside it.

**Comment by victorbalssa** [comment]
Thanks @elissonsilva85, I will add this feature in the release `0.6.0`

**Comment by GNeras** [comment]
While there isn't full support for split transactions, would it be possible to show the already existing transaction splits as different items on the transaction list? It would be more helpful than only showing part of the transaction.

**Comment by victorbalssa** [comment]
I'm working on this. 
should be ready soon.
