### ISSUE TITLE
Switch to monthly view results in "Invalid date NaN."

### ISSUE THREAD

**Issue by truehumandesign** [victorbalssa/abacus#77]
If I switch from Quarterly View to Monthly View I receive two error messages.
"Something went wrong - Request failed with status code 422".
The heading of the App shows "Invalid date NaN." - Feb 1.2023 - Invalid date
I am using iOS 16.3 and the App-Version is 0.5.0

**Comment by victorbalssa** [comment]
Thanks @truehumandesign,
Hot fix deployed.
