### ISSUE TITLE
Feature Request: dark mode

### ISSUE THREAD

**Issue by fate8383** [victorbalssa/abacus#85]
Please pretty please dark mode support :)

**Comment by carvalholeo** [comment]
Hey @victorbalssa, do you need some help with this feature? Maybe I can think in something to implement this (and I'd love to have dark mode too).

**Comment by victorbalssa** [comment]
Hey @carvalholeo, it's always appreciated! I will review any PR made to this repo and I've been pretty busy lately, I haven’t  started working on this.

**Comment by victorbalssa** [comment]
@fate8383 
@carvalholeo 
Abacus version `0.7.0` is deployed.

It supports Dark mode and iPad with new UI.

Feedbacks really appreciated!

**Comment by fate8383** [comment]
> @fate8383 
> @carvalholeo 
> Abacus version `0.7.0` is deployed.
> 
> It supports Dark mode and iPad with new UI.
> 
> Feedbacks really appreciated!
> 

So far so good, I am loving it. Tried add/remove transaction, works well. Thanks a lot!
