### ISSUE TITLE
App not available on Europe App Store

### ISSUE THREAD

**Issue by am93** [victorbalssa/abacus#88]
**Describe the bug**
Not a bug, but missing feature - application is currently unavailable on European App Store.

**To Reproduce**
1. Try to open App Store Link on EU account

**Expected behavior**
Download and install the application.

**Screenshots**
/

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.4.1
 - Version 16.4.1
 
**Additional context**
Is there any plan to release the app on EU App Store ? Is there any way to install the app without App Store in EU ?

**Comment by dwiprawira** [comment]
It also unavailable on Indonesian App Store. Do you have any plan to release the apps world wide?

**Comment by victorbalssa** [comment]
Hey @dwiprawira @am93, 
My Apple Developer Account expired yesterday, I plan to pay the fees next week.
Will notify here when the App is back online.
Victor
