### ISSUE TITLE
Feature request: Add foreign amount, tags and notes to create transaction view

### ISSUE THREAD

**Issue by klejejs** [victorbalssa/abacus#95]
I think the title is self-explanatory. I believe these would be very convenient to have while creating transactions.

P.S. Sorry, I was not sure how to create a feature request in any other way.

**Comment by victorbalssa** [comment]
Planning this for next version: `0.8.0`.

**Comment by vegardhw** [comment]
I guess this will also apply to edit existing transaction view? 🙂
